# Translations template for glance.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the glance project.
#
# Translators:
# Mario Cho <hephaex@gmail.com>, 2014
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: glance 13.0.0.0rc2.dev36\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2016-10-06 15:52+0000\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2016-03-24 12:38+0000\n"
"Last-Translator: SeYeon Lee <sy_lee@kr.ibm.com>\n"
"Language: ko-KR\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"Generated-By: Babel 2.0\n"
"X-Generator: Zanata 3.7.3\n"
"Language-Team: Korean (South Korea)\n"

#, python-format
msgid ""
"%(image_id)s: field %(key)s differs (source is %(master_value)s, destination "
"is %(slave_value)s)"
msgstr ""
"%(image_id)s: 필드 %(key)s이(가) 다름(소스는 %(master_value)s, 대상은 "
"%(slave_value)s)"

msgid ""
"/v3 controller is deprecated and will be removed from glance-api soon. "
"Remove the reference to it from glance-api-paste.ini configuration file and "
"use Glance Artifact Service API instead"
msgstr ""
"/v3 컨트롤러는 더 이상 사용되지 않으므로 glance-api에서 곧 제거됩니다. "
"glance-api-paste.ini 구성 파일에서 참조를 제거하고 대신 Glance Artifact "
"Service API를 사용하십시오."

#, python-format
msgid "Access denied to image %(id)s but returning 'not found'"
msgstr "이미지 %(id)s에 대한 액세스가 거부되었지만 '찾을 수 없음'이 리턴됨"

#, python-format
msgid "An optional task has failed, the failure was: %s"
msgstr "옵션 작업이 실패했습니다. 실패 내용: %s"

#, python-format
msgid "Artifact with id=%s is not accessible"
msgstr "id=%s인 아티팩트에 액세스할 수 없음"

#, python-format
msgid "Artifact with id=%s not found"
msgstr "id=%s인 아티팩트를 찾을 수 없음"

msgid "Artifact with the specified type, name and version already exists"
msgstr "지정된 유형, 이름, 버전을 사용하는 아티팩트가 이미 있음"

#, python-format
msgid ""
"Artifact with the specified type, name and version already has the direct "
"dependency=%d"
msgstr ""
"지정된 유형, 이름, 버전을 사용하는 아티팩트에 이미 직접  종속성= %d이(가) 있"
"음"

#, python-format
msgid ""
"Artifact with the specified type, name and versions already has the direct "
"dependency=%s"
msgstr ""
"지정된 유형, 이름, 버전을 사용하는 아티팩트에 이미 직접  종속성=%s이(가) 있음"

msgid "Attempted to modify image user did not own."
msgstr "사용자가 소유하지 않은 이미지를 수정하려고 시도했습니다."

#, python-format
msgid "Cached image file '%s' doesn't exist, unable to delete"
msgstr "캐시된 이미지 파일 '%s'이(가) 없음, 삭제할 수 없음"

#, python-format
msgid "Can't load artifact %s: load disabled in config"
msgstr "아티팩트 %s을(를) 로드할 수 없음: 구성에서 로드가 비활성화됨"

#, python-format
msgid "Can't load artifact %s: not in available_plugins list"
msgstr "아티팩트 %s을(를) 로드할 수 없음: available_plugins 목록에 없음"

#, python-format
msgid "Could not find image %s"
msgstr "이미지 %s을(를) 찾을 수 없음"

#, python-format
msgid ""
"Could not find schema properties file %s. Continuing without custom "
"properties"
msgstr ""
"스키마 특성 파일 %s을(를) 찾을 수 없습니다. 사용자 지정 특성 없이 계속합니다."

#, python-format
msgid "Could not find task %s"
msgstr "작업 %s을(를) 찾을 수 없음"

#, python-format
msgid "Could not find task info %s"
msgstr "작업 정보 %s을(를) 찾을 수 없음"

msgid "Deadlock detected. Retrying..."
msgstr "데드락 발견됨, 재시도중 "

#, python-format
msgid "Duplicate entry for values: %s"
msgstr "중복된 엔트리 값: %s"

#, python-format
msgid "Expected table %(tbl)s was not found in DB."
msgstr "예상 테이블 %(tbl)s을(를) DB에서 찾을 수 없습니다."

#, python-format
msgid ""
"Failed to activate image %s in registry. About to delete image bits from "
"store and update status to 'killed'."
msgstr ""
"레지스트리에서 이미지 %s을(를) 활성화하는 데 실패했습니다. 곧 저장소에서 이미"
"지 비트를 삭제하고 상태를 'killed'로 업데이트합니다."

#, python-format
msgid "Failed to decrypt location value for image %(image_id)s"
msgstr "이미지 %(image_id)s의 위치 값을 암호 해제하는 데 실패"

#, python-format
msgid "Failed to delete blob %s in store from URI"
msgstr "URI에서 저장소의 blob %s을(를) 삭제하는 데 실패"

#, python-format
msgid "Failed to delete file %(path)s. Got error: %(e)s"
msgstr "파일 %(path)s을(를) 삭제하지 못했습니다. 오류 발생: %(e)s"

#, python-format
msgid "Failed to delete image %s in store from URI"
msgstr "URI에서 저장소의 이미지 %s을(를) 삭제하는 데 실패"

#, python-format
msgid "Failed to find task %(task_id)s. Reason: %(reason)s"
msgstr "작업 %(task_id)s을(를) 찾지 못했습니다. 이유: %(reason)s"

msgid "Failed to successfully cache all images in queue."
msgstr "대기열에서 모든 이미지를 성공적으로 캐시하지 못했습니다."

#, python-format
msgid ""
"Fetch of cache file failed (%(e)s), rolling back by moving "
"'%(incomplete_path)s' to '%(invalid_path)s'"
msgstr ""
"캐시 파일 가져오기 실패%(e)s), '%(incomplete_path)s'을(를) "
"'%(invalid_path)s'(으)로 이동하여 롤백"

#, python-format
msgid "Forbidden to create task. Reason: %(reason)s"
msgstr "작업 생성이 금지되었습니다. 이유: %(reason)s"

#, python-format
msgid "Forbidden to get task %(task_id)s. Reason: %(reason)s"
msgstr "작업 %(task_id)s 가져오기가 금지되었습니다. 이유: %(reason)s"

msgid "Id not in sort_keys; is sort_keys unique?"
msgstr "ID가 sort_keys에 없습니다. sort_keys가 고유합니까?"

#, python-format
msgid "Image '%s' is not active. Not caching."
msgstr "이미지 '%s'이(가) 활성이 아닙니다. 캐시되지 않습니다."

#, python-format
msgid ""
"Image cache driver '%(driver_module)s' failed to configure. Got error: "
"'%(config_err)s"
msgstr ""
"이미지 캐시 드라이버 '%(driver_module)s'을(를) 구성하지 못했습니다. 오류 발"
"생: '%(config_err)s"

#, python-format
msgid ""
"Image cache driver '%(driver_name)s' failed to load. Got error: "
"'%(import_err)s."
msgstr ""
"이미지 캐시 드라이버 '%(driver_name)s'을(를) 로드하지 못했습니다. 오류 발생: "
"'%(import_err)s."

#, python-format
msgid "Invalid marker. Image %(id)s could not be found."
msgstr "올바르지 않은 마커입니다. 이미지 %(id)s을(를) 찾을 수 없습니다."

#, python-format
msgid "Invalid membership association specified for image %(id)s"
msgstr "이미지 %(id)s에 대해 올바르지 않은 멤버십 연관이 지정됨"

#, python-format
msgid "Member %(id)s not found"
msgstr "구성원 %(id)s 발견되지 않음"

#, python-format
msgid "Metadata tag not found for id %s"
msgstr "ID %s에 대한 메타데이터 태그를 찾을 수 없음"

#, python-format
msgid "No metadata found for image '%s'"
msgstr " image의 메어 자료가 없음 '%s'"

#, python-format
msgid ""
"One or more image locations couldn't be scrubbed from backend. Leaving image "
"'%s' in 'pending_delete' status"
msgstr ""
"백엔드에서 하나 이상의 이미지 위치를 삭제할 수 없습니다. 이미지 '%s'의 상태"
"를 'pending_delete'로 남겨 둠"

#, python-format
msgid "Show level %s is not supported in this operation"
msgstr "이 조작에서는 표시 레벨 %s이(가) 지원되지 않음"

#, python-format
msgid "Task %(task_id)s failed with exception %(error)s"
msgstr "작업 %(task_id)s에 실패하고 예외 %(error)s 발생"

msgid "The `eventlet` executor has been deprecated. Use `taskflow` instead."
msgstr ""
"`eventlet` 실행자는 더 이상 사용되지 않습니다. 대신 `taskflow`를 사용하십시"
"오."

#, python-format
msgid ""
"The conversion format is None, please add a value for it in the config file "
"for this task to work: %s"
msgstr "변환 포맷이 None임, 이 태스크를 통해 작업할 구성 파일에 값 추가: %s"

msgid "Unable to get deleted image"
msgstr "삭제된 이미지를 가져올 수 없음"

#, python-format
msgid "Unable to get deleted task %s"
msgstr "삭제된 작업 %s을(를) 가져올 수 없음"

msgid "Unable to get unowned image"
msgstr "소유하지 않은 이미지를 가져올 수 없음"

#, python-format
msgid "Unrecognised child %s"
msgstr "인식되지 않은 하위 %s"

#, python-format
msgid ""
"User %(user)s attempted to upload an image of size %(size)d that will exceed "
"the quota. %(remaining)d bytes remaining."
msgstr ""
"사용자 %(user)s이(가) 할당량을 초과하는 %(size)d 크기의 이미지를 업로드하려 "
"했습니다. %(remaining)d바이트가 남아 있습니다."

#, python-format
msgid ""
"User %(user)s attempted to upload an image of unknown size that will exceed "
"the quota. %(remaining)d bytes remaining."
msgstr ""
"사용자 %(user)s이(가) 할당량을 초과하는 알 수 없는 크기의 이미지를 업로드하"
"려 했습니다. %(remaining)d바이트가 남아 있습니다."

#, python-format
msgid "User lacks permission to share image %(id)s"
msgstr "사용자가 이미지 %(id)s을(를) 공유할 권한이 없음"
